name: Testing
on:
  push:
    branches:
    - actions-test
    
jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - name: Get the version
        run: |
          $VERSION="0.0.${{ github.run_number }}"
          if ("${{ github.ref }}".startsWith("refs/tags/v")) {
            $VERSION="${{ github.ref }}".substring('refs/tags/v'.length)
          }
          echo VERSION=$VERSION | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Validate version
        run: |
          echo "More Testing - ${{ env.VERSION }}"
          echo "Testing - $env:VERSION"
