name: Testing
on:
  push:
    branches:
    - actions-test
    
jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - name: Get the version
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch
          git checkout -m origin/${{ github.ref_name }} installer.wxs
          git checkout -m origin/${{ github.ref_name }} LICENSE.rtf
          dir
